# Generated by Django 4.2.6 on 2023-10-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_petlist_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlist',
            name='date_added',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
