# Generated by Django 4.2.6 on 2023-10-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_petlist_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petlist',
            name='age',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='state',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='petlist',
            name='suburb',
        ),
        migrations.AlterField(
            model_name='petlist',
            name='text',
            field=models.TextField(),
        ),
    ]
