# Generated by Django 4.2.6 on 2023-10-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_petlist_age_remove_petlist_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlist',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
