# Generated by Django 4.2.4 on 2023-10-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_petlist_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlist',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
