# Generated by Django 4.2.4 on 2023-10-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_petlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlist',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
